
"use client";

import React, { useState, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Form, FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { getAllAchievements, Achievement, addAchievement, updateAchievement, deleteAchievement } from "@/lib/data";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import Image from 'next/image';
import { enhanceText, EnhanceTextInput, EnhanceTextOutput } from '@/ai/flows/generate-photo-details-flow';
import { PlusCircle, Trash, Pencil, Bot } from 'lucide-react';
import { Badge } from '@/components/ui/badge';


const achievementSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1, { message: "Title is required" }),
  description: z.string().min(1, { message: "Description is required" }),
  date: z.string().refine((val) => !isNaN(Date.parse(val)), { message: "Invalid date format" }),
  photoUrl: z.string().url({ message: "Please enter a valid URL." }),
});

type AchievementFormValues = z.infer<typeof achievementSchema>;

export default function AchievementsManagementPage() {
  const [achievements, setAchievements] = useState<Achievement[]>([]);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiTopic, setAiTopic] = useState('');
  const { toast } = useToast();

  const fetchAchievements = async () => {
    const data = await getAllAchievements();
    setAchievements(data);
  };

  useEffect(() => {
    fetchAchievements();
  }, []);

  const form = useForm<AchievementFormValues>({
    resolver: zodResolver(achievementSchema),
    defaultValues: {
      title: "",
      description: "",
      date: "",
      photoUrl: "https://placehold.co/600x400.png",
    },
  });

  const onSubmit = async (data: AchievementFormValues) => {
    const { id, ...achievementData } = data;
    try {
      if (id) {
        await updateAchievement(id, achievementData);
        toast({ title: "Achievement Updated", description: "The achievement has been successfully updated." });
      } else {
        await addAchievement(achievementData);
        toast({ title: "Achievement Added", description: "The new achievement has been recorded." });
      }
      fetchAchievements();
      setIsDialogOpen(false);
      form.reset();
    } catch (error) {
      toast({ title: "Error", description: "Something went wrong.", variant: "destructive" });
    }
  };

  const handleEdit = (achievement: Achievement) => {
    form.reset(achievement);
    setIsDialogOpen(true);
  };
  
  const handleDelete = async (id: string) => {
    try {
      await deleteAchievement(id);
      fetchAchievements();
      toast({ title: "Achievement Deleted", description: "The achievement has been removed.", variant: "destructive" });
    } catch (error) {
       toast({ title: "Error", description: "Something went wrong.", variant: "destructive" });
    }
  };

  const handleGenerate = async () => {
    if (!aiTopic) {
        toast({ title: "Topic Required", description: "Please enter a topic to generate content.", variant: "destructive" });
        return;
    }

    setIsAiLoading(true);
    try {
        const enhanced: EnhanceTextOutput = await enhanceText({ topic: aiTopic, context: 'achievement' });
        form.setValue('title', enhanced.title, { shouldValidate: true });
        form.setValue('description', enhanced.description, { shouldValidate: true });
        toast({ title: "Content Generated", description: "The title and description have been generated by AI." });
    } catch (error) {
        toast({ title: "AI Generation Failed", description: "Could not generate content.", variant: "destructive" });
    } finally {
        setIsAiLoading(false);
    }
  };
  
  const AchievementActions = ({ achievement }: { achievement: Achievement }) => (
     <div className="flex gap-2">
       <Button variant="outline" size="sm" onClick={() => handleEdit(achievement)}>
        <Pencil className="h-4 w-4 mr-2" />
        Edit
      </Button>
        <AlertDialog>
          <AlertDialogTrigger asChild>
              <Button variant="destructive" size="sm">
                <Trash className="h-4 w-4 mr-2" />
                Delete
              </Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you sure?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone. This will permanently delete the achievement.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={() => handleDelete(achievement.id)}>Delete</AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
    </div>
  );


  return (
    <div className="flex flex-1 flex-col gap-4 md:gap-8">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Achievements</CardTitle>
            <CardDescription>Showcase your club's accomplishments and milestones.</CardDescription>
          </div>
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
               <Button size="sm" onClick={() => {
                  form.reset({
                    id: undefined,
                    title: "",
                    description: "",
                    date: "",
                    photoUrl: "https://placehold.co/600x400.png",
                  });
                  setAiTopic('');
                  setIsDialogOpen(true);
                }}>
                <PlusCircle className="h-4 w-4 mr-2" />
                Add Achievement
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
              <DialogHeader>
                <DialogTitle>{form.getValues("id") ? 'Edit Achievement' : 'Add New Achievement'}</DialogTitle>
              </DialogHeader>
               <div className="flex-grow overflow-y-auto pr-4 -mr-4">
                <Form {...form}>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                     <FormField
                      control={form.control}
                      name="photoUrl"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Photo URL</FormLabel>
                          <FormControl>
                            <Input placeholder="https://placehold.co/600x400.png" {...field} />
                          </FormControl>
                           <FormMessage />
                        </FormItem>
                      )}
                    />
                    <Card className="bg-muted/50 p-4">
                      <div className="space-y-2">
                          <p className="text-sm font-medium">Generate with AI</p>
                          <p className="text-xs text-muted-foreground">
                            Provide a topic and let AI write the title and description for you.
                          </p>
                          <div className="flex gap-2">
                            <Textarea 
                                placeholder="e.g., 'We won the state football championship against the rivals.'" 
                                value={aiTopic}
                                onChange={(e) => setAiTopic(e.target.value)}
                                className="flex-grow"
                            />
                            <Button type="button" variant="outline" onClick={handleGenerate} disabled={isAiLoading}>
                                {isAiLoading ? 'Generating...' : <> <Bot className="h-4 w-4 mr-2"/> Generate </>}
                            </Button>
                          </div>
                      </div>
                    </Card>
                     <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <FormField
                        control={form.control}
                        name="title"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Title</FormLabel>
                            <FormControl>
                                <Input placeholder="Tournament Champions" {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                        <FormField
                        control={form.control}
                        name="date"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Date</FormLabel>
                            <FormControl>
                                <Input type="date" {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                    </div>
                     <FormField
                      control={form.control}
                      name="description"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Description</FormLabel>
                          <FormControl>
                            <Textarea placeholder="Won the regional tournament..." {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <DialogFooter className="sticky bottom-0 bg-background py-4 -mx-6 px-6 border-t">
                      <DialogClose asChild>
                        <Button type="button" variant="ghost">Cancel</Button>
                      </DialogClose>
                      <Button type="submit">Save Achievement</Button>
                    </DialogFooter>
                  </form>
                </Form>
              </div>
            </DialogContent>
          </Dialog>
        </CardHeader>
        <CardContent>
           {/* Mobile View */}
          <div className="grid gap-4 md:hidden">
            {achievements.map((achievement) => (
              <Card key={achievement.id}>
                <div className="relative aspect-video w-full">
                  <Image src={achievement.photoUrl} alt={`Photo for ${achievement.title}`} fill className="object-cover rounded-t-lg" sizes="100vw" />
                </div>
                <CardHeader>
                  <CardTitle>{achievement.title}</CardTitle>
                  <p className="text-sm text-muted-foreground">{new Date(achievement.date).toLocaleDateString()}</p>
                </CardHeader>
                <CardContent className="space-y-2">
                  <p className="text-sm text-muted-foreground line-clamp-3">{achievement.description}</p>
                </CardContent>
                <CardFooter>
                  <AchievementActions achievement={achievement} />
                </CardFooter>
              </Card>
            ))}
          </div>
          {/* Desktop View */}
          <div className="hidden md:block">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Photo</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {achievements.map((achievement) => (
                  <TableRow key={achievement.id}>
                      <TableCell>
                           <div className="relative h-16 w-16 rounded-md overflow-hidden">
                             <Image src={achievement.photoUrl} alt={`Photo for ${achievement.title}`} fill className="object-cover" sizes="64px" />
                          </div>
                      </TableCell>
                    <TableCell className="font-medium">{achievement.title}</TableCell>
                    <TableCell className="text-muted-foreground line-clamp-2">{achievement.description}</TableCell>
                    <TableCell>{new Date(achievement.date).toLocaleDateString()}</TableCell>
                    <TableCell>
                      <AchievementActions achievement={achievement} />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
