
"use client";

import React, { useState, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Form, FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { getAllPhotos, Photo, addPhoto, updatePhoto, deletePhoto, addNotification } from "@/lib/data";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Switch } from "@/components/ui/switch";
import Image from 'next/image';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { enhanceText, EnhanceTextInput, EnhanceTextOutput } from '@/ai/flows/generate-photo-details-flow';
import { PlusCircle, Trash, Pencil, Edit, Bot } from 'lucide-react';


const photoSchema = z.object({
  id: z.string().optional(),
  url: z.string().url({ message: "Please enter a valid URL." }),
  title: z.string().optional(),
  description: z.string().optional(),
  isSliderPhoto: z.boolean().default(false),
  sendNotification: z.boolean().default(true),
});

type PhotoFormValues = z.infer<typeof photoSchema>;

export default function GalleryManagementPage() {
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiTopic, setAiTopic] = useState('');
  const { toast } = useToast();

  const fetchPhotos = async () => {
    const data = await getAllPhotos();
    setPhotos(data);
  };

  useEffect(() => {
    fetchPhotos();
  }, []);

  const form = useForm<PhotoFormValues>({
    resolver: zodResolver(photoSchema),
    defaultValues: {
      url: "https://placehold.co/600x400.png",
      isSliderPhoto: false,
      title: '',
      description: '',
      sendNotification: true,
    },
  });

  const onSubmit = async (data: PhotoFormValues) => {
    const { id, sendNotification, ...photoData } = data;
    try {
      if (id) {
        await updatePhoto(id, photoData);
        toast({ title: "Photo Updated", description: "The photo has been successfully updated." });
      } else {
        const newPhotoData = {
          ...photoData,
          uploadedAt: new Date().toISOString(),
        };
        const newPhoto = await addPhoto(newPhotoData);
        toast({ title: "Photo Added", description: "The new photo has been added to the gallery." });
        
        if (sendNotification) {
          await addNotification({
            title: `New Photo Added to Gallery`,
            description: newPhoto.title || "A new photo has been added to the gallery. Check it out!",
            link: '/gallery'
          });
          toast({ title: "Notification Sent", description: "Users have been notified about the new photo." });
        }
      }
      fetchPhotos();
      setIsDialogOpen(false);
      form.reset();
    } catch (error) {
       toast({ title: "Error", description: "Something went wrong.", variant: "destructive" });
    }
  };

  const handleEdit = (photo: Photo) => {
    form.reset({ ...photo, sendNotification: false });
    setAiTopic('');
    setIsDialogOpen(true);
  };
  
  const handleDelete = async (id: string) => {
    try {
      await deletePhoto(id);
      fetchPhotos();
      toast({ title: "Photo Deleted", description: "The photo has been removed from the gallery.", variant: "destructive" });
    } catch (error) {
       toast({ title: "Error", description: "Something went wrong.", variant: "destructive" });
    }
  };

  const handleGenerate = async () => {
    if (!aiTopic) {
        toast({ title: "Topic Required", description: "Please enter a topic to generate content.", variant: "destructive" });
        return;
    }

    setIsAiLoading(true);
    try {
        const enhanced: EnhanceTextOutput = await enhanceText({ topic: aiTopic, context: 'gallery' });
        form.setValue('title', enhanced.title, { shouldValidate: true });
        form.setValue('description', enhanced.description, { shouldValidate: true });
        toast({ title: "Content Generated", description: "The title and description have been generated by AI." });
    } catch (error) {
        toast({ title: "AI Generation Failed", description: "Could not generate content.", variant: "destructive" });
    } finally {
        setIsAiLoading(false);
    }
  };

  const PhotoActions = ({ photo }: { photo: Photo }) => (
    <div className="flex gap-2">
       <Button variant="outline" size="sm" onClick={() => handleEdit(photo)}>
         <Pencil className="h-4 w-4 mr-2" />
         Edit
      </Button>
       <AlertDialog>
          <AlertDialogTrigger asChild>
             <Button variant="destructive" size="sm">
                <Trash className="h-4 w-4 mr-2" />
                Delete
              </Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you sure?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone. This will permanently delete the photo.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={() => handleDelete(photo.id)}>Delete</AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
    </div>
  );

  return (
    <div className="flex flex-1 flex-col gap-4 md:gap-8">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Gallery Management</CardTitle>
            <CardDescription>Add, edit, and manage photos in your gallery.</CardDescription>
          </div>
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
               <Button size="sm" onClick={() => {
                  form.reset({
                    id: undefined,
                    url: "https://placehold.co/600x400.png",
                    isSliderPhoto: false,
                    title: '',
                    description: '',
                    sendNotification: true,
                  });
                  setAiTopic('');
                  setIsDialogOpen(true);
                }}>
                <PlusCircle className="h-4 w-4 mr-2" />
                Add Photo
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
              <DialogHeader>
                <DialogTitle>{form.getValues("id") ? 'Edit Photo' : 'Add New Photo'}</DialogTitle>
              </DialogHeader>
               <div className="flex-grow overflow-y-auto pr-4">
                <Form {...form}>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                    <FormField
                      control={form.control}
                      name="url"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Photo URL</FormLabel>
                          <FormControl>
                            <Input placeholder="https://placehold.co/600x400.png" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <Card className="bg-muted/50 p-4">
                      <div className="space-y-2">
                          <p className="text-sm font-medium">Generate with AI</p>
                          <p className="text-xs text-muted-foreground">
                            Provide a topic and let AI write the title and description for you.
                          </p>
                          <div className="flex gap-2">
                            <Textarea 
                                placeholder="e.g., 'Team celebrating after a big win at the finals.'" 
                                value={aiTopic}
                                onChange={(e) => setAiTopic(e.target.value)}
                                className="flex-grow"
                            />
                            <Button type="button" variant="outline" onClick={handleGenerate} disabled={isAiLoading}>
                                {isAiLoading ? 'Generating...' : <> <Bot className="h-4 w-4 mr-2"/> Generate</>}
                            </Button>
                          </div>
                      </div>
                    </Card>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <FormField
                        control={form.control}
                        name="title"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Title (Optional)</FormLabel>
                            <FormControl>
                              <Input placeholder="A nice title for the photo" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      <FormField
                        control={form.control}
                        name="description"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Description (Optional)</FormLabel>
                            <FormControl>
                              <Textarea placeholder="A short description of the photo" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                     <FormField
                      control={form.control}
                      name="isSliderPhoto"
                      render={({ field }) => (
                        <FormItem className="flex flex-row items-center justify-between rounded-lg border p-3 shadow-sm">
                          <div className="space-y-0.5">
                            <FormLabel>Show on Homepage Slider</FormLabel>
                          </div>
                          <FormControl>
                            <Switch
                              checked={field.value}
                              onCheckedChange={field.onChange}
                            />
                          </FormControl>
                        </FormItem>
                      )}
                    />
                     {!form.getValues("id") && (
                      <FormField
                        control={form.control}
                        name="sendNotification"
                        render={({ field }) => (
                          <FormItem className="flex flex-row items-center justify-between rounded-lg border p-3 shadow-sm">
                            <div className="space-y-0.5">
                              <FormLabel>Send Notification</FormLabel>
                               <p className="text-xs text-muted-foreground">Notify users about this new photo.</p>
                            </div>
                            <FormControl>
                              <Switch
                                checked={field.value}
                                onCheckedChange={field.onChange}
                              />
                            </FormControl>
                          </FormItem>
                        )}
                      />
                    )}
                    <DialogFooter className="sticky bottom-0 bg-background py-4 -mx-6 px-6 border-t">
                      <DialogClose asChild>
                        <Button type="button" variant="ghost">Cancel</Button>
                      </DialogClose>
                      <Button type="submit">Save Photo</Button>
                    </DialogFooter>
                  </form>
                </Form>
              </div>
            </DialogContent>
          </Dialog>
        </CardHeader>
        <CardContent>
          {/* Mobile View */}
          <div className="grid gap-4 md:hidden">
            {photos.map((photo) => (
              <Card key={photo.id}>
                <div className="relative aspect-video w-full">
                  <Image src={photo.url} alt={photo.title || ''} fill className="object-cover rounded-t-lg" sizes="100vw"/>
                </div>
                <CardHeader>
                  <CardTitle className="truncate">{photo.title || 'Untitled'}</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                   <p className="text-sm text-muted-foreground line-clamp-2">{photo.description || 'No description'}</p>
                   <div>
                    <Badge variant={photo.isSliderPhoto ? "default" : "outline"}>
                      {photo.isSliderPhoto ? "On Slider" : "Not on Slider"}
                    </Badge>
                  </div>
                </CardContent>
                <CardFooter>
                  <PhotoActions photo={photo} />
                </CardFooter>
              </Card>
            ))}
          </div>

          {/* Desktop View */}
          <div className="hidden md:block">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Photo</TableHead>
                  <TableHead>Details</TableHead>
                  <TableHead>On Slider</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {photos.map((photo) => (
                  <TableRow key={photo.id}>
                    <TableCell>
                      <div className="relative h-16 w-24 rounded-md overflow-hidden">
                        <Image src={photo.url} alt={photo.title || `Photo ${photo.id}`} fill className="object-cover" sizes="96px" />
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium truncate">{photo.title || 'Untitled'}</div>
                      <div className="text-sm text-muted-foreground line-clamp-2">{photo.description || 'N/A'}</div>
                    </TableCell>
                    <TableCell>
                       {photo.isSliderPhoto ? (
                         <Badge>Yes</Badge>
                        ) : (
                         <Badge variant="outline">No</Badge>
                        )}
                      </TableCell>
                    <TableCell className="text-right">
                      <PhotoActions photo={photo} />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
